name: CSV scrape automation hourly

on:
    schedule:
        - cron: '0 * * * *'
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
            matrix:
                python-version: [3.10.9]
        
        steps:
        - uses: actions/checkout@v3
          with:
            ref: main
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v3
          with:
              python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
        - name: Run Django management command
          run: python manage.py csv_scrape
          working-directory: Site/bc_weather_station_dashboard
        - name: Commit and push changes
          run: |
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add -A
              git commit -m "Update database" || exit 0
              git push https://${{ secrets.GITHUB_TOKEN }}@github.com/carsondrobe/Fellas.git
